"""
export_ollama.py  —  Export fine-tuned model to Ollama
=======================================================
After fusing LoRA adapters (finetune.py --fuse), this script
creates an Ollama Modelfile and registers the model locally
so you can use it directly in chat.py.

Usage:
    python scripts/export_ollama.py
    python scripts/export_ollama.py --model-name my-science-llm
"""

import os
import sys
import subprocess
import argparse
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

from rich.console import Console
from rich.panel import Panel

console = Console()

FUSED_PATH    = Path("./models/fused-model")
MODELFILE_PATH = Path("./models/Modelfile")

SCIENCE_SYSTEM_PROMPT = """You are an expert scientific research assistant specializing in the user's personal science library. You have been fine-tuned on their collection of scientific papers, textbooks, and research documents.

Your capabilities:
- Answer detailed questions about scientific topics in the user's library
- Summarize research papers and chapters
- Explain complex scientific concepts clearly
- Help with citation and literature review
- Assist with scientific writing

Always cite the relevant document or paper when making specific claims. If uncertain, acknowledge the limitation. Use precise scientific language appropriate to the field."""


def check_fused_model():
    """Verify the fused model exists."""
    if not FUSED_PATH.exists():
        console.print(Panel(
            "[red]Fused model not found.[/]\n\n"
            "Run fine-tuning and fusion first:\n"
            "  1. [bold]python scripts/finetune.py[/]\n"
            "  2. [bold]python scripts/finetune.py --fuse[/]",
            title="Missing model",
            border_style="red"
        ))
        sys.exit(1)
    console.log(f"Fused model found: [green]{FUSED_PATH}[/]")


def create_modelfile(model_name: str):
    """Create Ollama Modelfile for the fine-tuned model."""
    # Ollama needs GGUF format — convert from MLX if needed
    modelfile_content = f"""# Science LLM — Fine-tuned Mistral 7B
# Generated by export_ollama.py

FROM {FUSED_PATH.resolve()}

SYSTEM \"\"\"{SCIENCE_SYSTEM_PROMPT}\"\"\"

# Inference parameters optimized for scientific Q&A
PARAMETER temperature 0.1
PARAMETER top_p 0.9
PARAMETER top_k 40
PARAMETER repeat_penalty 1.1
PARAMETER num_ctx 8192
PARAMETER stop "<s>"
PARAMETER stop "</s>"
PARAMETER stop "[INST]"
PARAMETER stop "[/INST]"
"""
    MODELFILE_PATH.parent.mkdir(parents=True, exist_ok=True)
    MODELFILE_PATH.write_text(modelfile_content)
    console.log(f"Modelfile created: [green]{MODELFILE_PATH}[/]")
    return MODELFILE_PATH


def convert_to_gguf():
    """Convert MLX model to GGUF format for Ollama (if needed)."""
    gguf_path = FUSED_PATH / "model.gguf"
    if gguf_path.exists():
        console.log("GGUF file already exists, skipping conversion.")
        return gguf_path

    console.log("[bold]Converting MLX model to GGUF for Ollama...[/]")
    console.log("[dim]This requires llama.cpp — checking...[/]")

    # Check for llama.cpp convert script
    llama_convert = subprocess.run(
        ["which", "convert-hf-to-gguf.py"],
        capture_output=True, text=True
    )

    if llama_convert.returncode != 0:
        console.print(Panel(
            "[yellow]llama.cpp conversion tools not found.[/]\n\n"
            "Alternative approach: Use the Ollama direct MLX model\n"
            "The fused MLX model can be used directly with mlx-lm:\n\n"
            "  [bold]python -m mlx_lm.generate \\\n"
            "    --model ./models/fused-model \\\n"
            "    --prompt 'Your question here'[/]\n\n"
            "Or use the base Mistral model with LoRA adapters in chat.py\n"
            "by setting USE_LORA_ADAPTER=true in .env",
            title="Conversion Note",
            border_style="yellow"
        ))
        return None

    return gguf_path


def register_with_ollama(model_name: str, modelfile_path: Path):
    """Register the model with Ollama."""
    console.log(f"Registering [bold cyan]{model_name}[/] with Ollama...")

    try:
        result = subprocess.run(
            ["ollama", "create", model_name, "-f", str(modelfile_path)],
            capture_output=True, text=True, check=True
        )
        console.log("[green]Model registered with Ollama ✓[/]")
        return True
    except subprocess.CalledProcessError as e:
        console.print(f"[yellow]Ollama registration: {e.stderr}[/]")
        return False
    except FileNotFoundError:
        console.print("[yellow]Ollama not found. Install from: https://ollama.ai[/]")
        return False


def update_env(model_name: str):
    """Update .env to use the fine-tuned model."""
    env_path = Path(".env")
    if env_path.exists():
        content = env_path.read_text()
        # Update MODEL_NAME
        lines = content.splitlines()
        updated = []
        found = False
        for line in lines:
            if line.startswith("MODEL_NAME="):
                updated.append(f"MODEL_NAME={model_name}")
                found = True
            else:
                updated.append(line)
        if not found:
            updated.append(f"MODEL_NAME={model_name}")
        env_path.write_text("\n".join(updated) + "\n")
        console.log(f"[green]Updated .env: MODEL_NAME={model_name}[/]")


def main():
    parser = argparse.ArgumentParser(description="Export fine-tuned model to Ollama")
    parser.add_argument("--model-name", type=str, default="science-mistral",
                        help="Name for the Ollama model (default: science-mistral)")
    args = parser.parse_args()

    console.print(Panel(
        "[bold cyan]Exporting Fine-tuned Model to Ollama[/]\n"
        f"Model name: [bold]{args.model_name}[/]",
        border_style="cyan"
    ))

    check_fused_model()
    convert_to_gguf()
    modelfile = create_modelfile(args.model_name)
    registered = register_with_ollama(args.model_name, modelfile)

    if registered:
        update_env(args.model_name)
        console.print(Panel(
            f"[bold green]Fine-tuned model ready![/]\n\n"
            f"Model: [bold]{args.model_name}[/]\n\n"
            "Start chatting:\n"
            "  [bold]python scripts/chat.py[/]\n\n"
            f"Or test directly:\n"
            f"  [bold]ollama run {args.model_name}[/]",
            title="Export Complete ✓",
            border_style="green"
        ))
    else:
        console.print(Panel(
            "Fine-tuned model (MLX format) is at:\n"
            f"  [bold]{FUSED_PATH}[/]\n\n"
            "Use it directly with mlx-lm:\n"
            "  [bold]python -m mlx_lm.generate \\\n"
            "    --model ./models/fused-model \\\n"
            "    --prompt '[INST] Your question [/INST]'[/]",
            title="Model Available (MLX)",
            border_style="cyan"
        ))


if __name__ == "__main__":
    main()
